import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./pages/layout/Header";
import Footer from "./pages/layout/Footer";

export const metadata: Metadata = {
  title: "exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pt-36 w-full px-28">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
